language: c # not actually c, but this has less dependencies than default ruby language

sudo: required

notifications:
  slack:
    on_success: always
  email: false

services:
  - docker

before_install:
  - docker pull boiyaa/yamllint
  - docker pull nginx
  - git submodule init
  - git submodule update

script:
  - cp .env.sample .env
  - "script/test"
