version: '3'

services:
   mqtt:
     image: eclipse-mosquitto
     ports:
       - "1883:1883"
       - "9001:9001"
     volumes:
       - mqtt-data:/mosquitto/data
       - ./mqtt/config:/mosquitto/config
   harmony-api:
     image: jonmaddox/harmony-api
     depends_on:
       - mqtt
     ports:
       - 8282:8282
     volumes:
        - ./harmony-api/config:/config
     network_mode: "host"

   home-assistant:
     image: homeassistant/home-assistant
     depends_on:
       - mqtt
     ports:
       - 8123:8123
     volumes:
       - ./homeassistant/config:/config
     network_mode: "host"

   #sonos:
   #  image: chrisns/docker-node-sonos-http-api
   #  network_mode: "host"


volumes:
    mqtt-data:
