version: '3'

services:
  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt-data:/mosquitto/data
      - ./mqtt/config:/mosquitto/config

  harmony-api:
    image: jonmaddox/harmony-api
    restart: always
    depends_on:
      - mqtt
    ports:
      - 8282:8282
    volumes:
      - ./harmony-api/config:/config
    network_mode: "host"

  homeassistant:
    image: homeassistant/home-assistant:0.82.1
    #build: ./homeassistant/src
    restart: always
    #depends_on:
    #  - apcupsd
    #  - harmony-api
    #  - mqtt
    #  - sonos
    #  - influxdb
    ports:
      - 8123:8123
    volumes:
      - ./homeassistant/config:/config
    tty: true # so we get colors
    network_mode: "host"

  nginx:
    #image: nginx
    build:
      context: ./nginx/
      args:
        - external_hostname=$EXTERNAL_HOSTNAME
        - internal_hostname=$INTERNAL_HOSTNAME
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - homeassistant
    extra_hosts:
      - "homeassistant:${DOCKER_IP}"

  avahi-alias:
    privileged: true # required for dbus access
    image: flqw/avahi-alias:latest
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    command:
      - homeassistant.local

  sonos:
    image: chrisns/docker-node-sonos-http-api
    restart: always
    ports:
      - 5005:5005
    volumes:
      - ./sonos/settings:/app/settings
      - ./sonos/clips:/app/static/clips
      - sonos-cache:/app/cache
      - ./sonos/presets:/app/presets
    network_mode: "host"

  apcupsd:
    image: retrohunter/apcupsd-cgi
    restart: always
    ports:
      - 3551:3551
    devices:
      - /dev/usb/hiddev0:/dev/usb/hiddev0

  samba:
    image: dperson/samba
    restart: always
    command: -n -s videos;/mount/videos -g "netbios name = picklehome" -u kodi;${SAMBA_KODI_PASSWORD}
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
    volumes:
      - ./data:/mount:ro
    network_mode: "host"

  prometheus:
    #image: prom/prometheus
    build:
      context: ./prometheus/
      args:
        - bearer_token=$HOMEASSISTANT_PROMETHEUS_BEARER_TOKEN
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus-data
    network_mode: "host"
    #entrypoint: "/bin/sh"
    
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter
    restart: always
    user: root
    privileged: true
    ports:
      - "9100:9100"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/host:ro,rslave" 
    network_mode: "host"
    pid: "host"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  cadvisor:
    image: google/cadvisor:latest
    restart: always
    privileged: true
    ports:
      - "8080:8080"
    network_mode: "host"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/snap/docker/current/run/docker:/var/lib/docker:ro"

  influxdb:
    image: influxdb:1.4
    container_name: influxdb
    ports:
      - 8086:8086
      - 8083:8083
    volumes:
      - influxdb-data:/var/lib/influxdb
      # NOTE if you don't have one, you can use:
      #   docker run --rm influxdb influxd config > influxdb.conf
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command: -config /etc/influxdb/influxdb.conf
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - influxdb
      - prometheus
    restart: always
    network_mode: host

  alertmanager:
    #image: prom/alertmanager
    build:
      context: ./alertmanager/
      args:
        - slack_channel=$ALERTMANAGER_SLACK_CHANNEL
        - slack_webhook_url=$ALERTMANAGER_SLACK_WEBHOOK_URL
    network_mode: host
    #entrypoint: /bin/sh
    #volumes:
    #  - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: always
    expose:
      - 9093

  airconnect:
    restart: always
    build: airconnect
    network_mode: host
    command:
      - "-d"
      - all=info
      - "-b"
      - ":49152"
      - "-x"
      - /config/config.xml
      - "-Z"
    volumes:
      - ./airconnect/config:/config

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ
      - PLEX_CLAIM
    network_mode: host
    volumes:
      - plex-config:/config
      - plex-transcode:/transcode
      - ./data:/data
  duckdns:
    restart: unless-stopped
    image: linuxserver/duckdns
    env_file:
      - .env.duckdns
    environment:
      - TZ
  certbot:
    image: certbot/dns-dnsimple
    network_mode: "none"
    volumes:
      - ./certbot/dnsimple.ini:/etc/dnsimple.ini
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-log:/var/logs/letsencrypt

volumes:
  mqtt-data:
  sonos-cache:
  prometheus-data:
  plex-transcode:
  plex-config:
  influxdb-data:
  grafana-data:
  certbot-etc:
  certbot-log:
  certbot-var:
