version: '3'

services:
  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt-data:/mosquitto/data
      - ./mqtt/config:/mosquitto/config

  homeassistant:
    image: homeassistant/home-assistant:0.82.1
    #build: ./homeassistant/src
    restart: always
    #depends_on:
    #  - apcupsd
    #  - harmony-api
    #  - mqtt
    #  - sonos
    #  - influxdb
    volumes:
      - ./homeassistant/config:/config
    tty: true # so we get colors
    network_mode: "host"

  nginx:
    build:
      context: ./nginx/
      args:
        - external_hostname=$EXTERNAL_HOSTNAME
        - internal_hostname=$INTERNAL_HOSTNAME
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - homeassistant
    extra_hosts:
      - "homeassistant:${DOCKER_IP}"

  avahi-alias:
    privileged: true # required for dbus access
    image: flqw/avahi-alias:latest
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    command:
      - homeassistant.local

  sonos:
    image: chrisns/docker-node-sonos-http-api
    restart: always
    ports:
      - 5005:5005
    volumes:
      - ./sonos/settings:/app/settings
      - ./sonos/clips:/app/static/clips
      - sonos-cache:/app/cache
      - ./sonos/presets:/app/presets
    network_mode: "host"

  apcupsd:
    image: retrohunter/apcupsd-cgi
    restart: always
    ports:
      - 3551:3551
    devices:
      - /dev/usb/hiddev0:/dev/usb/hiddev0

  prometheus:
    build:
      context: ./prometheus/
      args:
        - bearer_token=$HOMEASSISTANT_PROMETHEUS_BEARER_TOKEN
    restart: always
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus-data
    extra_hosts:
      - "homeassistant:${DOCKER_IP}"
      - "docker:${DOCKER_IP}"

  cadvisor:
    image: google/cadvisor:latest
    restart: always
    privileged: true
    ports:
      - "18080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/snap/docker/current/run/docker:/var/lib/docker:ro"

  influxdb:
    image: influxdb:1.4
    container_name: influxdb
    ports:
      - 8086:8086
      - 8083:8083
    volumes:
      - influxdb-data:/var/lib/influxdb
      # NOTE if you don't have one, you can use:
      #   docker run --rm influxdb influxd config > influxdb.conf
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command: -config /etc/influxdb/influxdb.conf
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - influxdb
      - prometheus
    restart: always

  alertmanager:
    build:
      context: ./alertmanager/
      args:
        - slack_channel=$ALERTMANAGER_SLACK_CHANNEL
        - slack_webhook_url=$ALERTMANAGER_SLACK_WEBHOOK_URL
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: always

  certbot:
    image: certbot/dns-dnsimple
    volumes:
      - ./certbot/dnsimple.ini:/etc/dnsimple.ini
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-log:/var/logs/letsencrypt

volumes:
  mqtt-data:
  sonos-cache:
  prometheus-data:
  influxdb-data:
  grafana-data:
  certbot-etc:
  certbot-log:
  certbot-var:
