services:
  dev:
    build:
      context: .
      args:
        USERNAME: technicalpickles
        USER_UID: 1000
        USER_GID: 1000
    container_name: dev
    hostname: picklelab-dev
    ports:
      - "2222:22"
    working_dir: /workspace
    restart: unless-stopped
    volumes:
      - ssh-host-keys:/etc/ssh/host_keys

volumes:
  ssh-host-keys:
