#!/bin/bash

set -x

container=$(docker-compose ps -q homeassistant 2>/dev/null)

if [[ -n "${container}" ]]; then
  bin/homeassistant --script check_config
  docker-compose stop homeassistant
fi

docker-compose up -d homeassistant

script/logs
