#!/bin/bash

set -e
set -x

bin/yamllint --strict --config-data '{extends: relaxed, rules: {line-length: disable}}' docker-compose.yml
docker-compose config --quiet
# FIXME need to figure out how to populate certbot-etc volume during CI
#bin/nginx -t
