services:
  cli:
    volumes:
      - /srv/data/obsidian-sync/config:/root/.config

  rpg:
    volumes:
      - /srv/data/obsidian-sync/config:/root/.config
      - /srv/data/obsidian-sync/vaults/rpg:/vault
