services:
  rpg:
    image: obsidian-sync
    build: .
    user: "1000:1000"
    init: true
    restart: unless-stopped
    volumes:
      - ob-config-rpg:/home/node/.config
      - rpg:/vault

  pickled-knowledge:
    image: obsidian-sync
    user: "1000:1000"
    init: true
    restart: unless-stopped
    volumes:
      - ob-config-pickled-knowledge:/home/node/.config
      - pickled-knowledge:/vault

volumes:
  ob-config-rpg:
  ob-config-pickled-knowledge:
  rpg:
  pickled-knowledge:
