services:
  rpg:
    volumes:
      - /srv/data/obsidian-sync/config/rpg:/home/node/.config
      - /srv/data/obsidian-sync/vaults/rpg:/vault

  pickled-knowledge:
    volumes:
      - /srv/data/obsidian-sync/config/pickled-knowledge:/home/node/.config
      - /srv/data/obsidian-sync/vaults/pickled-knowledge:/vault
