#!/usr/bin/env bash
# Deploy the second-brain-agent container on picklelab.
# Idempotent: safe to run on first setup or any subsequent deploy.
# Run from the repo root on the target host.
set -euo pipefail

REPO_DIR=/opt/homelab
SERVICE_DIR="$REPO_DIR/homelab/services/second-brain-agent"
DATA_DIR=/srv/data/second-brain-agent
CONTAINER_UID=1000
CONTAINER_GID=1000

cd "$REPO_DIR"

echo "==> Deploying commit $(git rev-parse --short HEAD)"

echo "==> Creating data directories on the volume"
# ssh/host_keys: sshd host keys (generated by entrypoint, survives redeploys so
#   SSH clients don't see a fingerprint change after a container rebuild).
# ts-state:  the ts-agent sidecar's Tailscale node identity (TS_STATE_DIR), so
#   the node persists across recreates instead of churning the device list.
# claude:    ~/.claude symlink target (Claude Code credentials + session state).
# tmux-resurrect: tmux-resurrect session saves (auto-restored on tmux start).
sudo mkdir -p \
  "$DATA_DIR/ssh/host_keys" \
  "$DATA_DIR/ts-state" \
  "$DATA_DIR/claude" \
  "$DATA_DIR/tmux-resurrect"
sudo chown -R "$CONTAINER_UID:$CONTAINER_GID" "$DATA_DIR"

echo "==> Linking systemd unit"
sudo ln -sf "$SERVICE_DIR/second-brain-agent.service" /etc/systemd/system/

echo "==> Reloading systemd and restarting service"
sudo systemctl daemon-reload
sudo systemctl enable second-brain-agent.service
sudo systemctl restart second-brain-agent.service

echo "==> Status"
systemctl status second-brain-agent.service --no-pager

TAILNET=$(tailscale status --json | jq -r '.CurrentTailnet.MagicDNSSuffix')
AGENT_HOST="second-brain-agent.${TAILNET}"

echo ""
echo "==> Waiting for the agent node's sshd at ${AGENT_HOST}:22"
for i in 1 2 3 4 5 6 7 8 9 10; do
  if timeout 2 bash -c "cat < /dev/null > /dev/tcp/${AGENT_HOST}/22" 2>/dev/null; then
    echo "    Reachable at ${AGENT_HOST}:22"
    echo ""
    echo "Done! Connect with: ssh technicalpickles@${AGENT_HOST}"
    echo "Then: tmux attach   (or tmux new -s main)"
    echo "Phone (mosh): mosh technicalpickles@${AGENT_HOST} then tmux attach"
    exit 0
  fi
  echo "    Waiting for the node (attempt $i/10)..."
  sleep 2
done

echo "    WARNING: ${AGENT_HOST}:22 not reachable after 10 attempts"
echo ""
echo "    Check the node registered:"
echo "      tailscale status | grep second-brain-agent"
echo "      docker compose -f compose.yaml -f compose.picklelab.yaml logs ts-agent"
echo "    First deploy only: approve the device at https://login.tailscale.com/admin/machines"
echo "    MagicDNS for a fresh node can lag a few seconds after approval."
